/// Mirrors `AppTheme` from feishin's `app-theme-types.ts`.
enum AppThemeId {
  ayuDark,
  ayuLight,
  catppuccinLatte,
  catppuccinMocha,
  defaultDark,
  defaultLight,
  dracula,
  everforestDark,
  everforestLight,
  githubDark,
  githubLight,
  glassyDark,
  gruvboxDark,
  gruvboxLight,
  highContrastDark,
  highContrastLight,
  materialDark,
  materialLight,
  monokai,
  nightOwl,
  nord,
  oneDark,
  rosePine,
  rosePineDawn,
  rosePineMoon,
  shadesOfPurple,
  solarizedDark,
  solarizedLight,
  tokyoNight,
  vscodeDarkPlus,
  vscodeLightPlus,
  zenburn,
}

/// Display labels, ported from `THEME_DATA` in `use-app-theme.ts`.
extension AppThemeIdLabel on AppThemeId {
  String get label => switch (this) {
    AppThemeId.ayuDark => 'Ayu Dark',
    AppThemeId.ayuLight => 'Ayu Light',
    AppThemeId.catppuccinLatte => 'Catppuccin Latte',
    AppThemeId.catppuccinMocha => 'Catppuccin Mocha',
    AppThemeId.defaultDark => 'Default Dark',
    AppThemeId.defaultLight => 'Default Light',
    AppThemeId.dracula => 'Dracula',
    AppThemeId.everforestDark => 'Everforest Dark',
    AppThemeId.everforestLight => 'Everforest Light',
    AppThemeId.githubDark => 'GitHub Dark',
    AppThemeId.githubLight => 'GitHub Light',
    AppThemeId.glassyDark => 'Glassy Dark',
    AppThemeId.gruvboxDark => 'Gruvbox Dark',
    AppThemeId.gruvboxLight => 'Gruvbox Light',
    AppThemeId.highContrastDark => 'High Contrast Dark',
    AppThemeId.highContrastLight => 'High Contrast Light',
    AppThemeId.materialDark => 'Material Dark',
    AppThemeId.materialLight => 'Material Light',
    AppThemeId.monokai => 'Monokai',
    AppThemeId.nightOwl => 'Night Owl',
    AppThemeId.nord => 'Nord',
    AppThemeId.oneDark => 'One Dark',
    AppThemeId.rosePine => 'Rosé Pine',
    AppThemeId.rosePineDawn => 'Rosé Pine Dawn',
    AppThemeId.rosePineMoon => 'Rosé Pine Moon',
    AppThemeId.shadesOfPurple => 'Shades of Purple',
    AppThemeId.solarizedDark => 'Solarized Dark',
    AppThemeId.solarizedLight => 'Solarized Light',
    AppThemeId.tokyoNight => 'Tokyo Night',
    AppThemeId.vscodeDarkPlus => 'VS Code Dark+',
    AppThemeId.vscodeLightPlus => 'VS Code Light+',
    AppThemeId.zenburn => 'Zenburn',
  };
}
